"""Add need_schedule and schedule_name fields to email_detection_details

Revision ID: 068e5b7bf7a0
Revises: 681d0169298a
Create Date: 2025-09-17 09:30:34.509961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068e5b7bf7a0'
down_revision = '681d0169298a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_detection_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('need_schedule', sa.Integer(), nullable=False, server_default='0', comment='是否需要日程：0-不需要，1-需要'))
        batch_op.add_column(sa.Column('schedule_name', sa.String(length=255), nullable=True, comment='日程名称'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_detection_details', schema=None) as batch_op:
        batch_op.drop_column('schedule_name')
        batch_op.drop_column('need_schedule')
    # ### end Alembic commands ###
