"""add schedule_time field

Revision ID: 1e2de8983f6a
Revises: 068e5b7bf7a0
Create Date: 2025-09-17 09:53:34.236399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2de8983f6a'
down_revision = '068e5b7bf7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_detection_details', sa.Column('schedule_time', sa.DateTime(), nullable=True, comment='日程时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_detection_details', 'schedule_time')
    # ### end Alembic commands ###
