"""Create user_email_bindings table

Revision ID: 36a0919dd72b
Revises: 4376c599d300
Create Date: 2025-09-04 13:57:10.015141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a0919dd72b'
down_revision = '4376c599d300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='绑定记录唯一标识'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('provider_id', sa.Integer(), nullable=False, comment='邮箱厂商ID'),
    sa.Column('provider_name', sa.String(length=100), nullable=False, comment='邮箱厂商名称'),
    sa.Column('email_address', sa.String(length=255), nullable=False, comment='邮箱地址'),
    sa.Column('auth_code', sa.String(length=500), nullable=False, comment='授权码'),
    sa.Column('imap_server', sa.String(length=255), nullable=False, comment='IMAP服务器地址'),
    sa.Column('smtp_server', sa.String(length=255), nullable=False, comment='SMTP服务器地址'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('reserved_field1', sa.String(length=255), nullable=True, comment='保留字段1'),
    sa.Column('reserved_field2', sa.String(length=255), nullable=True, comment='保留字段2'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email_bindings_email_address'), 'user_email_bindings', ['email_address'], unique=False)
    op.create_index(op.f('ix_user_email_bindings_is_active'), 'user_email_bindings', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_email_bindings_is_deleted'), 'user_email_bindings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_email_bindings_provider_id'), 'user_email_bindings', ['provider_id'], unique=False)
    op.create_index(op.f('ix_user_email_bindings_user_id'), 'user_email_bindings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email_bindings_user_id'), table_name='user_email_bindings')
    op.drop_index(op.f('ix_user_email_bindings_provider_id'), table_name='user_email_bindings')
    op.drop_index(op.f('ix_user_email_bindings_is_deleted'), table_name='user_email_bindings')
    op.drop_index(op.f('ix_user_email_bindings_is_active'), table_name='user_email_bindings')
    op.drop_index(op.f('ix_user_email_bindings_email_address'), table_name='user_email_bindings')
    op.drop_table('user_email_bindings')
    # ### end Alembic commands ###
