"""Add headers field to emails table

Revision ID: 3fca05f78096
Revises: 102e38850e31
Create Date: 2025-09-07 13:15:53.926628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fca05f78096'
down_revision = '102e38850e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_email_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email_bindings_email_address'))
        batch_op.drop_index(batch_op.f('ix_user_email_bindings_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_email_bindings_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_user_email_bindings_provider_id'))
        batch_op.drop_index(batch_op.f('ix_user_email_bindings_user_id'))

    op.drop_table('user_email_bindings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email_bindings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('provider_id', sa.INTEGER(), nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('auth_code', sa.VARCHAR(length=500), nullable=False),
    sa.Column('imap_server', sa.VARCHAR(length=255), nullable=False),
    sa.Column('smtp_server', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('reserved_field1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reserved_field2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('provider_display_name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_email_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email_bindings_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email_bindings_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email_bindings_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email_bindings_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email_bindings_email_address'), ['email_address'], unique=False)

    # ### end Alembic commands ###
