"""Add email_suffix field to EmailProvider

Revision ID: 4376c599d300
Revises: 9c0e3d05ae34
Create Date: 2025-09-04 13:31:23.855995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4376c599d300'
down_revision = '9c0e3d05ae34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_suffix', sa.String(length=100), nullable=False, comment='邮箱后缀，如@gmail.com'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_providers', schema=None) as batch_op:
        batch_op.drop_column('email_suffix')
    # ### end Alembic commands ###
