"""Add detection_stage and parallel_detection_completed fields

Revision ID: 681d0169298a
Revises: 950682245d6e
Create Date: 2025-09-09 10:12:31.931087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681d0169298a'
down_revision = '950682245d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_detection_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detection_stage', sa.Integer(), nullable=False, server_default='1', comment='检测阶段：1-第一阶段，2-第二阶段，3-第三阶段，4-第四阶段'))
        batch_op.add_column(sa.Column('parallel_detection_completed', sa.Boolean(), nullable=False, server_default='0', comment='第二阶段并行检测是否全部完成'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_detection_details', schema=None) as batch_op:
        batch_op.drop_column('parallel_detection_completed')
        batch_op.drop_column('detection_stage')
    # ### end Alembic commands ###
