"""Add headers field to emails table manually

Revision ID: 950682245d6e
Revises: 3fca05f78096
Create Date: 2025-09-07 13:16:15.674731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950682245d6e'
down_revision = '3fca05f78096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headers', sa.Text(), nullable=True, comment='邮件完整头信息'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('headers')
    # ### end Alembic commands ###
